### ISSUE TITLE
Unable to run the programm

### ISSUE THREAD

**Issue by sowjanyavenum** [jexp/neo4j-graphviz#1]
I wanted to create graphs using neo4j and grapghviz...but i am unable to run the program even to know how does it works.... but unfortunately facing these errors.....

ERROR 1:
just im giving command: node render.js password
This is the error I get"
*************
graph.jpg jpg neato MATCH path = (a)-[r]->(b) RETURN path LIMIT 100
{ [Error: write EPIPE] code: 'EPIPE', errno: 'EPIPE', syscall: 'write' }
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: spawn \usr\local\bin\neato ENOENT
    at exports._errnoException (util.js:893:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

This is the error I am facing...Can anyone help me out how to run the program 
ERROR 2:

and if i try to keep (in render.js)
ng.renderGraph("bolt://localhost:7474","neo4j",pwd,query,use,file);
Then it is saying the following error
***********************
C:\Users\neo4j-graphviz-master>node render.js password
graph.jpg jpg neato MATCH path = (a)-[r]->(b) RETURN path LIMIT 100
Driver instantiation failed { [Error: 101057795:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:openssl\ssl\s23_clnt.c:794:
] code: 'SessionExpired' }
{ [Error: 101057795:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:openssl\ssl\s23_clnt.c:794:
] code: 'SessionExpired' }

Can please anybody help me out it is very challenging..... !!

**Comment by ianwdunlop** [comment]
I had a similar issue because I did not have graphviz installed so it could not find the `neato` renderer. On Ubuntu and variants try `sudo apt-get install graphviz`. However, it will still be looking for it in `/usr/local/bin` rather than `/usr/bin`. I had to alter the following line in `neo4j-graphviz.js`:

```
-        g.setGraphVizPath( "/usr/local/bin" );
+        g.setGraphVizPath( "/usr/bin" );
```

**Comment by jexp** [comment]
Would probably make sense to detect it automatically.
